service: serverless-project

provider:
  name: aws
  runtime: nodejs6.10
  environment:
      DYNAMODB_TABLE: todos

custom:
  dynamodb:
    start:
      port: 8000
      migrate: true
      sharedDb: true

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: GET

  create:
      handler: todos/create.create
      events:
        - http:
            path: todos
            method: post
            cors: true

  get_all:
        handler: todos/get_all.getAll
        events:
          - http:
              path: todos
              method: get
              cors: true

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: text
            AttributeType: S
        KeySchema:
          - AttributeName: text
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-dynamodb-local
  - serverless-offline
